"""Pydantic schemas used across the voice interview platform."""

from __future__ import annotations

from datetime import datetime
from typing import Literal

from pydantic import BaseModel, Field


class Education(BaseModel):
    """Represents one education entry from a resume."""

    degree: str
    institution: str
    year: str | None = None


class ResumeData(BaseModel):
    """Structured resume data extracted from uploaded files."""

    skills: list[str] = Field(default_factory=list)
    experience_years: float = 0.0
    education: list[Education] = Field(default_factory=list)
    projects: list[str] = Field(default_factory=list)
    certifications: list[str] = Field(default_factory=list)


class Question(BaseModel):
    """Interview question generated by the LLM engine."""

    text: str
    expected_points: list[str]
    difficulty: Literal["easy", "medium", "hard"]
    category: Literal["technical", "behavioral", "problem_solving"]


class Evaluation(BaseModel):
    """Evaluation result for an answer."""

    score: float
    feedback: str


class CommunicationAnalysis(BaseModel):
    """Communication quality analysis output."""

    clarity: float
    confidence: float
    conciseness: float
    feedback: str


class InterviewStartRequest(BaseModel):
    """Interview start request payload."""

    jd: str
    candidate_name: str


class InterviewStartResponse(BaseModel):
    """Interview start response payload."""

    interview_id: str
    session_token: str
    questions_count: int
    estimated_duration: str


class TranscriptMessage(BaseModel):
    """One transcript message from interviewer or candidate."""

    role: Literal["interviewer", "candidate"]
    text: str
    timestamp: datetime


class ScoreBreakdown(BaseModel):
    """Calculated score breakdown."""

    technical: float
    communication: float
    problem_solving: float
    overall: float


class AssessmentReport(BaseModel):
    """Candidate assessment report output."""

    interview_id: str
    candidate_name: str
    overall_score: float
    technical_score: float
    communication_score: float
    problem_solving_score: float
    skills_match_percentage: float
    recommendation: str
    strengths: list[str]
    weaknesses: list[str]
    transcript: list[TranscriptMessage]
    pdf_url: str


class JDData(BaseModel):
    """Normalized JD model for scoring functions."""

    text: str
    skills: list[str] = Field(default_factory=list)
